### ISSUE TITLE
Kategorien / Tabs

### ISSUE THREAD

**Issue by Sioweb** [tbaddade/redaxo_sprog#12]
Es wäre super, wenn man die Begriffe in Tabs/Kategorien einteilen könnte. Ich stelle mir einfach vor dass man ein Feld "Tags" nach denen man filtern kann. Idealer Weise gleich so, dass bei KeyUp gleich Vorschläge von bereits vorhandenen Tags geliefert wird, damit man sich nicht unnötig vertippt.

**Comment by Sioweb** [comment]
Generell will ich nur Gruppieren.

Suchfeld braucht es nicht, das was ich meine ist ein Feld mit Name Tag. Wenn man da anfängt einen Tag einzutippen, bekommt man Tags aus bestehenden Platzhalter vorgeschlagen. Damit man sich nicht vertippt und keine extra Tabelle dafür braucht.

**Comment by alexplusde** [comment]
beim String Table Addon habe ich ein Namensschema benutzt, um eine Gruppierung zu erreichen, z.B.

modul:gallery:left
modul:gallery:right
modul:gallery:close

oder
template:search:legend
template:search:placeholder
template:search:button

Damit wurde der Kontext klarer.

Vielleicht wäre das auch ein Lösungsansatz, um Begriffe zu gruppieren und diese evtl. gesondert im Backend anzuzeigen / zu filtern.
