### ISSUE TITLE
nl2br bitte optional

### ISSUE THREAD

**Issue by VIEWSION** [tbaddade/redaxo_sprog#14]
Hi. Ich verwende spross auch für kleine html-snippets, wo die <br /> ziemlich lästig sind. Gut wäre, wenn man das nl2br optional global und oder individuell per Platzhalter setzen könnte. Man könnte es auch über den Platzhalter selbst lösen... z.B. so:

{{platzhalter|raw}}

**Comment by tbaddade** [comment]
Geh bei #23 weiter
