### ISSUE TITLE
sprog hängt sich auf

### ISSUE THREAD

**Issue by dtpop** [tbaddade/redaxo_sprog#16]
Redaxo 5.1, Watson (installiert, aktiviert, aber genauso inaktiviert), fast alle Addons sind deaktiviert.
Ein Aufruf im Backend macht
"ErrorException" thrown in /www/verzeichnis/redaxo/src/addons/sprog/lib/Sprog/Wildcard.php on line 23
Fatal error: Maximum execution time of 30 seconds exceeded
Frontend funktioniert.

sprog / wildcard_close_tag ist in der rex_config vorhanden.

Wenn ich die Zeile 23 durch

return ' }}';

ersetze, dann funktioniert das Backend.

**Comment by tbaddade** [comment]
Kannst du die komplette Fehlermeldung posten?

Und schau mal ob in der rex_config Tabelle die Einträge zu sprog vorhanden sind.

**Comment by dtpop** [comment]
Danke Thomas. Ich habe nochmal debuggt - ich war selber schuld. Ich habe in den Einstellungen das öffnende Tag gelöscht. Das darf man wohl nicht machen. Die Fehlermeldung gibt sonst keine weitere Info ..

"ErrorException" thrown in /www/anix.biz/redaxo/src/addons/sprog/lib/Sprog/Wildcard.php on line 23
Fatal error: Maximum execution time of 30 seconds exceeded
activate safe mode

Lg Wolfgang

**Comment by tbaddade** [comment]
Danke dir für die Rückmeldung.
