### ISSUE TITLE
Leerer Artikelname

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_sprog#18]
Wenn beide Synchronisierungswege (Kategorie->Artikel, Artikel->Kategorie) aktiviert sind, wird beim Erstellen einer neuen Kategorie kein Artikelname ausgefüllt:

![image](https://cloud.githubusercontent.com/assets/3855487/16042391/b7d66f4e-323a-11e6-971d-8675ed4eb4ed.png)

sind diese Funktionen generell im Sprachen-Addon richtig aufgehoben?

**Comment by olien** [comment]
Das Verhalten kann ich bestätigen.
(ich finde schon, dass das hier seine Berechtigung hat...)

**Comment by tbaddade** [comment]
Könntet ihr mal diese Datei ersetzen und schauen ob der Fehler noch existiert.
https://github.com/tbaddade/redaxo_sprog/blob/master/lib/Sprog/Sync.php

**Comment by olien** [comment]
Funktioniert bei mir!

**Comment by tbaddade** [comment]
fixed 5cfcc0b2c38c2bcf7c955667c60201e064e072f0
