### ISSUE TITLE
Fehlermeldung nach Deaktivierung der Checkbox 'Sprachen als Unternavigation einblenden'

### ISSUE THREAD

**Issue by isospin** [tbaddade/redaxo_sprog#19]
`Error while executing statement "SELECT DISTINCT a.id, a.wildcard AS wildcard, english.replace AS id1,deutsch.replace AS id2,.replace AS id3,.replace AS id4,magyar.replace AS id5,hrvatski.replace AS id6 FROM rex_sprog_wildcard AS a LEFT JOIN rex_sprog_wildcard AS english ON a.id = english.id AND english.clang_id = 1 LEFT JOIN rex_sprog_wildcard AS deutsch ON a.id = deutsch.id AND deutsch.clang_id = 2 LEFT JOIN rex_sprog_wildcard AS  ON a.id = .id AND .clang_id = 3 LEFT JOIN rex_sprog_wildcard AS  ON a.id = .id AND .clang_id = 4 LEFT JOIN rex_sprog_wildcard AS magyar ON a.id = magyar.id AND magyar.clang_id = 5 LEFT JOIN rex_sprog_wildcard AS hrvatski ON a.id = hrvatski.id AND hrvatski.clang_id = 6 ORDER BY wildcard! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS id3,.replace AS id4,magyar.replace AS id5,hrvatski.replace AS id6 FROM rex_sp' at line 1`

reinstallation war erfolglos. nach löschen und neu installation geht es wieder. und der fehler ist nicht reproduzierbar...

**Comment by tbaddade** [comment]
Der Name der Sprache mit der Id 4 war nicht vorhanden. Deshalb kam es scheinbar zum Fehler.

**Comment by isospin** [comment]
die sprache mit der id 3 ist български
da werde nutze ich wohl besser die neuen meta infos für sprachen.
danke!
