### ISSUE TITLE
Idee: "Glossar" Erweiterung

### ISSUE THREAD

**Issue by olien** [tbaddade/redaxo_sprog#22]
**Felder** 
- aktiv / inaktiv
- Begriff
- Definition
- Beschreibung
- Bild?

**Ausgabe (Module)**
- Erweiterung der Begriffe im Frontent (jeder Begriff soll nur einmal auf einer Seite ersetzt werden) und Darstellung der Definition im Tootltip. Evtl. Verlinkung auf eine Detailseite
- Ausgabe als übersichtliche Liste mit Ankern zu den einzelnen Buchstaben (A,B,C etc.)
- Ausgabe einer Tagcloud mit den eingetragenen Begriffen (verlinkt)

**Sonstiges**

Eigene Rechte, damit jemand auch "nur" das Glossar pflegen kann (sprachabhängig?)

**Comment by tbaddade** [comment]
@olien Ein Glossar hattest du jetzt bereits selbst erstellt oder?

**Comment by olien** [comment]
Hallo Thomas,

Es gibt ein Addon für die Eingabe. Für die Ausgaben habe ich noch nichts gemacht. 

Wenn du das in Sprog integrierst wäre das auf jeden Fall die bessere Lösung falls du dazu Lust hast... Ausgaben kann ja jeder selbst schreiben ;-) (Es gibt auch irgendwo ein Beispiel von Thomas Skerbis)

Grüße 
Oliver

**Comment by olien** [comment]
hab das so (grad gefunden :-)

**Comment by skerbis** [comment]
Na ja, was ich da gemacht habe war mehr oder minder ne FAQ ... ein Beispiel wie man yForm-Tabellen ausgibt.
