### ISSUE TITLE
Template geht bei Wechsel des Onlinestatus verloren

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_sprog#24]
Voraussetzung: in der Konfiguration die Option "Templates zwischen den Sprachen synchronisieren" aktivieren. Ich habe zwei Sprachen: Deutsch und Englisch. Der Artikel (nicht Kategorie, denn bei den Kategorien funktioniert alles korrekt) ist in beiden Sprachen online. Nun schalte ich den Artikel in der Sprache Deutsch auf "Offline". Dann ist in der Sprache Englisch "KEIN TEMPLATE" eingetragen.

**Comment by tbaddade** [comment]
Ich kann es nicht nachvollziehen. Könntest du mal mit der GH Version testen ob es in der Zwischenzeit gefixed wurde.

**Comment by TobiasKrais** [comment]
Perfekt: ist in der aktuellen Git Version behoben. Danke!
