### ISSUE TITLE
best practice: Sprog-Übersetzungen in Javascript

### ISSUE THREAD

**Issue by alxndr-w** [tbaddade/redaxo_sprog#27]
Anwendungsfall: Website in mehreren Sprachen + sämtliche Lightbox-Skripte o.ä., die Schaltflächen für "Zurück", "Weiter" dynamisch generieren.

Wie gehe ich da am besten vor?
- Anfrage des Begriffs über einen preparierten Artikel?
- Ausgabe eines JSON-Arrays im Footer der HTML-Datei?
- Ausgabe in einem versteckten HTML-Element, z.B. <span data-key="translation" data-ctype="0" data-sprog="Übersetzung"></span>?

Am coolsten wäre es, wenn Sprog sich so weit in Redaxo einklinken könnte, dass man einen Platzhalter über `/sprog/clang/key1,key2,key3` per URL-Aufruf anfragen kann und diesen dann kommagetrennt oder in einem JSON-Array ersetzt zurück bekommt.

**Comment by tbaddade** [comment]
Die einfachste Variante die jetzt ginge wäre

```javascript
<script>
var sprog = new Object;
sprog.Name = '{{ name }}';
</script>
```

Aber sicherlich könnte man das vereinfachen. :)

**Comment by alexplusde** [comment]
Also das geht bereits?

**Comment by tbaddade** [comment]
> Also das geht bereits?

Ich meine schon. Gib doch mal Feedback ob es tatsächlich klappt. Ich selbst brauchte es noch nie in JS.

**Comment by alexplusde** [comment]
Ich hab mal wieder etwas zu weit um die Ecke gedacht, so ist das für den Moment ziemlich praktikabel. 

Gedanken dazu:
- Mann müsste wahrscheinlich noch für die Fälle, in denen Anführungszeichen verwendet werden, escapen.
- Es wäre klasse, wenn man einen Namespace definieren könnte, um sich einen Teil der Datenbank direkt ausgeben zu lassen und in ein JS-Objekt zu schreiben, statt jeden Begriff von Hand in den Quellcode einzutragen.

**Comment by tbaddade** [comment]
Meine erster Gedanke wäre jetzt etwas in diese Richtung gewesen.

```javascript
<script>
var sprog = <?= Sprog::getJsonArray($startsWith = 'js.') ?>
</script>
```

Kann nur passieren, dass man dadurch die Platzhalter doppelt anlegt.

Checkbox beim Platzhalter finde ich wiederum ungünstig, weil die Platzhalter zumeist auch von Redakteuren betreut werden. Haken weg, fliegt dir das Javascript um die Ohren.

**Comment by alexplusde** [comment]
Checkbox fände ich auch doof an der Stelle.

**Comment by tbaddade** [comment]
@alexplusde ist das noch aktuell bzw. hast du in der Vergangenheit Anregungen finden können?
Ich habe es tatsächlich bis heute immer noch nicht gebrauchen können.

**Comment by alexplusde** [comment]
Gerade nicht - für alle mehrsprachigen Seiten habe ich es anders gelöst und im Moment setzen wir nur DE-Sites um.

vlt. einfach in die Readme aufnehmen als Ansatz und dann hier zumachen.
