### ISSUE TITLE
Darstellungsproblem bei öffnenden und schließenden Tag 

### ISSUE THREAD

**Issue by georgkaser** [tbaddade/redaxo_sprog#29]
Sehe nichts im Textfeld (siehe Grafik)

Browser Firefox, Betriebssystem Fedora 24, KDE 5.7

![screenshot_20160928_123401](https://cloud.githubusercontent.com/assets/6472869/18910361/ee3354f4-8577-11e6-98ac-9d75beff6b4e.png)

**Comment by Hirbod** [comment]
Kann ich bestätigen!
