### ISSUE TITLE
Key-Abgleich mit xoutputfilter

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_sprog#32]
Keys, die in XOutputFilter angelegt werden, sollten nicht in der Liste der nicht ersetzten Platzhalter von Sprog auftauchen und vice versa.

https://github.com/FriendsOfREDAXO/xoutputfilter/issues/20

**Comment by tbaddade** [comment]
Weiß jetzt nicht was du meinst. Laut @aeberhard sollte der Outputfilter keine Sprachersetzungen mitbringen wie es bereits Sprog macht. Muss mir das AddOn mal installieren

**Comment by alexplusde** [comment]
Ist in Ordnung, die keys für Frontend-Ersetzungen können komplett frei definiert werden. 

Das Problem ist, wenn man das gleiche Schema für output-Ersetzungen und Sprog-Ersetzungen einsetzt, bspw.

###sprogkey###
###outputfilterkey###

Dann taucht ###outputfilterkey### in der Liste der nicht vergebenen Sprog-Keys auf.

Workaround: Ein anderes Ersetzungsschema für outputfilter verwenden.

**Comment by tbaddade** [comment]
@alexplusde Du solltest einfach gänzlich auf den outputfilter setzen.
