### ISSUE TITLE
sprog deaktiviert pjax

### ISSUE THREAD

**Issue by ynamite** [tbaddade/redaxo_sprog#36]
Hab gerade versucht herauszufinden wieso PJAX nicht geht. Schuld war am Ende sprog.

Kann man das nicht anders lösen?

https://github.com/tbaddade/redaxo_sprog/blob/master/boot.php#L124

Edit: Ursache scheint gefixt zu sein, siehe https://github.com/redaxo/redaxo/issues/607

**Comment by skerbis** [comment]
Die Alert-DIV-Geschichte ist gefixt. Dennoch schade, dass PJAX deaktiviert wird.

**Comment by ynamite** [comment]
Ich denke sprog wird das wieder rausnehmen, gemäss https://github.com/redaxo/redaxo/issues/607 scheint die Ursache des Problems behoben.

**Comment by ynamite** [comment]
Wie sähe ich ob's geht oder nicht? :)

**Comment by tbaddade** [comment]
> Wie sähe ich ob's geht oder nicht? :)

:) … das ganze `if` löschen … Dann eine Kategorie umbenennen und schauen ob auch der Artikelname geändert wurde. Funktioniert natürlich nur, wenn das Syncen unter Einstellungen gesetzt ist.

**Comment by ynamite** [comment]
funzt :) PJAX aktiv und if gelöscht.
sorry, gerade mit dem kopf wo anders, hätte ich auch selber drauf kommen können
