### ISSUE TITLE
sprog steigt bei einfacher Klammer aus

### ISSUE THREAD

**Issue by dtpop** [tbaddade/redaxo_sprog#37]
Wenn ein Platzhalter eine einfache öffnende Klammer enthält (ohne schließende Klammer, wird eine leere Seite ausgeliefert. Folgender Eintrag steht im Error-Log:
preg_replace(): Compilation failed: missing ) at offset 42	
redaxo\src\addons\sprog\lib\Sprog\Wildcard.php

**Comment by tbaddade** [comment]
Kann ich mit der aktuellen GH-Version nicht nachvollziehen. Eventuell könntest du bei dir nochmals testen, sobald die Version online ist und einfach das Issue wieder öffnen.
