### ISSUE TITLE
Vorschlag zur Übersichtlichkeit

### ISSUE THREAD

**Issue by olien** [tbaddade/redaxo_sprog#4]
Auf der Seite ?page=sprog/wildcard

die Darstellung der "Platzhalter" verbreitern und dafür evtl. die "Ersetzung" verkleinern (jeweils 1 col?)

**Comment by tbaddade** [comment]
Hmm … ich finde das die Platzhalter eher weniger Platz brauchen als die Ersetzungen. Hier kommt teilweise ganzer Fließtext rein. Daher schließe ich mal.
