### ISSUE TITLE
Standardkonfiguration bei Installation festlegen

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_sprog#42]
Wenn sprog installiert wird ist es nicht Einsatzbereit. Erst nach dem ersten Speichern der Konfiguration.  Es wäre super, wenn bei der Installation die Standard Placeholder in die Optionen geschrieben werden.

**Comment by tbaddade** [comment]
Hier[1] wird die Config ausgelesen und als Fallback imm die geschweiften Klammern zurückgegeben. Könnte das bei dir noch eine andere Ursache haben.

[1]
https://github.com/tbaddade/redaxo_sprog/blob/master/lib/Sprog/Wildcard.php#L18
https://github.com/tbaddade/redaxo_sprog/blob/master/lib/Sprog/Wildcard.php#L23

**Comment by TobiasKrais** [comment]
Danke für die schnelle Antwort. Das ist ja seltsam. Ich untersuche das mal genauer und melde mich gegebenfalls. Danke!
