### ISSUE TITLE
Bug: Rechtemanagement

### ISSUE THREAD

**Issue by dima-clicksports** [tbaddade/redaxo_sprog#46]
Hi Com,

bei Benutzern deren Rolle keine Adminrechte besitzen, wird das Eingabefeld im AddOn nicht angezeigt, weil in der Eingabemaske auf Adminrechte überprüft wird.

**Comment by tbaddade** [comment]
> bei Benutzern deren Rolle keine Adminrechte besitzen, wird das Eingabefeld im AddOn nicht angezeigt, weil in der Eingabemaske auf Adminrechte überprüft wird.

Korrekt. Zumeist legt der Developer/Admin den Platzhalter im Code fest.
