### ISSUE TITLE
editiermodus - zwischen sprachen springen 

### ISSUE THREAD

**Issue by steri-rex** [tbaddade/redaxo_sprog#48]
es wäre super wenn man im editermodus ist und auf eine andere sprache klickt auch im edtiermodus bleibt - also gleich das wort in der anderen sprache verändern kann.
im moment kommt man immer auf die übersicht zurück.

**Comment by tbaddade** [comment]
Schnelle Abhilfe schafft das Ausblenden der Unternavigation.

**Comment by steri-rex** [comment]
vielen dank - wusste ich nicht das es das gibt!
