### ISSUE TITLE
Liste der noch nicht ersetzten Platzhalter

### ISSUE THREAD

**Issue by Sioweb** [tbaddade/redaxo_sprog#5]
Ho! 

Das ist ein super feature. Wenn ich aber den Platzhalter hinzufüge, wäre es super wenn dieser gleich ohne Klammern oder sonstige Platzhaltermarkierungen eingefügt wird. 

Was mir noch aufgefallen ist, dass der Platzhalter nicht aus der Liste entfernt wird: 

![bildschirmfoto 2015-12-21 um 11 14 24](https://cloud.githubusercontent.com/assets/1318048/11928509/6951abea-a7d4-11e5-963a-cec1d4eb9d1b.png)

Ich hab Templates und Modules neu erstellt. Aber der Vorschlag bleibt.

**Comment by tbaddade** [comment]
> Was mir noch aufgefallen ist, dass der Platzhalter nicht aus der Liste entfernt wird
> Ich hab Templates und Modules neu erstellt. Aber der Vorschlag bleibt.

Die Liste enthält aktuell nur Platzhalter, die in den Artikeln vorhanden sind. Es werden keine Tempalte oder Module durchsucht.

**Comment by isospin** [comment]
ist mir auch gerade aufgefallen. in der liste der nicht ersetzten platzhalter stehen welche, die sehr wohl angelegt sind. hab gerade schon verschiedenes probiert, kriege diese einträge nicht gelöscht.
gibt es da einen trick?

**Comment by tbaddade** [comment]
D.h. die tauchen oben und unten in der Liste auf?

Wo befinden sich die Platzhalter und wie heißen diese?

**Comment by isospin** [comment]
ja, die tauchen oben und unten auf 
und befinden sich in einem modul eingabefeld mit yform stuff:

> email|email|{{contact_email_placeholder}}||[no_db]|
textarea|message|{{contact_message_placeholder}}||[no_db]
submit|label|{{contact_send}}|[no_db]|submit|


![spog](https://cloud.githubusercontent.com/assets/1148347/16484949/756a9502-3ebc-11e6-92be-28dfc26f6ef7.png)

**Comment by tbaddade** [comment]
> email|email|{{contact_email_placeholder}}||[no_db]|

Könntest du mal zum Testen es so notieren, also mit Leerzeichen drum herum
`email|email| {{contact_email_placeholder}} ||no_db|`

PS: Das `no_db` schreib man ohne die `[ ]`

**Comment by isospin** [comment]
bringt leider nichts...

**Comment by alexwenz** [comment]
Habe das gleiche Problem.

**Comment by isospin** [comment]
> {{ platzhalter }} geht
{{platzhalter}] geht nicht

kann ich bestätigen. 
danke für den tipp!

**Comment by tbaddade** [comment]
Die `geht nicht` Variante beinhaltet ein `]`. Daran liegt es nicht?

**Comment by alexwenz** [comment]
Ups. Sorry. Der hat sich eingeschlichen. Liegt meines Erachtens wirklich "nur" an den Leerzeichen.

**Comment by isospin** [comment]
nein, an den eckicken klammern liegt es nicht. entscheidend sind die Leerzeichen:
`{{ platzhalter }}`
Die müssen da sein.
