### ISSUE TITLE
error nach hinzugefügten sprachen

### ISSUE THREAD

**Issue by steri-rex** [tbaddade/redaxo_sprog#51]
Hallo,
habe gerade 2 Sprachen unter System hinzugefügt und nun kommt diese Fehlermeldung wenn ich auf das Sprog Addon klicke:

`rex_sql_exception | Error while executing  statement "SELECT DISTINCT a.id, a.wildcard AS wildcard, clang1.replace  AS id1,clang2.replace AS id2,clang3.replace AS id3 FROM  rex_sprog_wildcard AS a LEFT JOIN rex_sprog_wildcard AS clang1 ON a.id =  clang1.id AND clang1.clang_id = 1 LEFT JOIN rex_sprog_wildcard AS  clang2 ON a.id = clang2.id AND clang2.clang_id = 2 LEFT JOIN  rex_sprog_wildcard AS clang3 ON a.id = clang3.id AND clang3.clang_id = 3  WHERE 1  ORDER BY wildcard"! SQLSTATE[42000]: Syntax error or access  violation: 1104 The SELECT would examine more than MAX_JOIN_SIZE rows;  check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if  the SELECT is okay | redaxo/src/core/lib/sql/sql.php | zeile 340`

**Comment by tbaddade** [comment]
Strato?
Wieviele Platzhalter sind in der ersten Sprache definiert?

**Comment by tbaddade** [comment]
Leider keine weiteren Infos bekommen, daher close
