### ISSUE TITLE
Countable-Warning (php 7.2) 

### ISSUE THREAD

**Issue by isospin** [tbaddade/redaxo_sprog#55]
beim speichern der artikel metadaten gibt es unter php7.2 folgende warning:
```
count(): Parameter must be an array or an object that implements Countable
redaxo/src/addons/sprog/lib/Sprog/Extension.php:42
```

https://github.com/tbaddade/redaxo_sprog/blob/0d74d9a7efd976844f6ec15d462baccc7e2c2401/lib/Sprog/Extension.php#L42

**Comment by olien** [comment]
In Sprog 1.2.0 ist der Fehler noch (wieder?) da:

`10.03.2020 07:42:51 | Warning | count(): Parameter must be an array or an object that implements Countable | redaxo/src/addons/sprog/lib/Sprog/Extension.php | 55`


REDAXO | 5.10.0-beta2
PHP 7.2.14

**Comment by alexplusde** [comment]
Ich hab den aktuell auch ständig.
