### ISSUE TITLE
 Spanish translations are not yet displayed, please

### ISSUE THREAD

**Issue by nandes2062** [tbaddade/redaxo_sprog#57]
I still can not see the translations into Spanish, I think they have to do a new release, something similar happened to me before: https://github.com/FriendsOfREDAXO/redactor2/issues/124#issuecomment-387871680 ,

**Comment by tbaddade** [comment]
[Version 1.2.0](https://github.com/tbaddade/redaxo_sprog/releases/tag/1.2.0) is online
