### ISSUE TITLE
Rekursives Ersetzen

### ISSUE THREAD

**Issue by alexplusde** [tbaddade/redaxo_sprog#61]
Lässt sich das irgendwie umsetzen?

z.B. 
```
{{name}} = Kevin
{{meldung}} = Ihre Nachricht an {{name}} wurde erfolgreich zugestellt.
```

Output:
```
Ihre Nachricht an Kevin wurde erfolgreich zugestellt.
```

**Comment by tbaddade** [comment]
> Lässt sich das irgendwie umsetzen?

```
{{name}} = Kevin
{{meldung}} = Ihre Nachricht an %s wurde erfolgreich zugestellt.

<?php
$name = sprogcard('name');
echo '{{ meldung|format('.$name.') }}';
```

**Comment by alexplusde** [comment]
Das geht jedoch nur in der PHP-Schreibweise, oder?

**Comment by tbaddade** [comment]
> Das geht jedoch nur in der PHP-Schreibweise, oder?

ja

**Comment by alexplusde** [comment]
Und auch nur für 2 Level mit dem Beispiel. Rekursiv wäre schon hilfreich, um Textbausteine in anderen wieder zu verwenden.

**Comment by tbaddade** [comment]
Ich kann verstehen das man das gern haben möchte, sehe hier aber Probleme in der Umsetzung.

Wenn du gern einen PR beisteuern magst, kannst du das Issue gern wieder öffnen.
