### ISSUE TITLE
Sprachvariante prüfen ob Inhalte vorhanden

### ISSUE THREAD

**Issue by meugel** [tbaddade/redaxo_sprog#62]
Wie kann ich bei der Ausgabe via PHP prüfen ob ein Platzhalter einen Inhalt hat oder nicht? Ich möchte nämlich keine "leeren" Platzhalter ausgeben.
`<?php if ('{{ Platzhalter }}' != '') echo '{{ Platzhalter }}'; ?>` funktioniert leider nicht.

**Comment by eaCe** [comment]
@meugel du kannst die Funktion `sprogcard()` nutzen. 

```if(sprogcard("Platzhalter ")) {}```

**Comment by meugel** [comment]
Danke, das war die Lösung!
Ich benutze die Platzhalter als Filter in einem Isotope-Masonry Container, und wenn ich da leere Platzhalter habe, funktioniert die Filterung nicht mehr.
