### ISSUE TITLE
Sprog funktioniert nur nach erstmaligem Speichern der Einstellungen

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_sprog#63]
Wenn SProg komplett neu installiert wird muss die Konfiguration einmalig gespeichert werden, damit SProg funktioniert. Sonst werden die Platzhalter nicht ersetzt.

**Comment by tbaddade** [comment]
Kann ich nicht nachvollziehen. Könnte aber an deiner Schreibweise der Platzhalter liegen.

Hier wird ein Fallback notiert, sofern die Conti nichts zurückgibt:
https://github.com/tbaddade/redaxo_sprog/blob/master/lib/Sprog/Wildcard.php#L18
https://github.com/tbaddade/redaxo_sprog/blob/master/lib/Sprog/Wildcard.php#L23

**Comment by tbaddade** [comment]
Ich habs eben in einem anderen Projekt getestet … Dort war die Config auch noch nicht in der DB. Daher schließe ich erst einmal. Wenn das bei dir dennoch u.U. nicht funktioniert können wir das gern wieder öffnen.

_Btw: SProg => Sprog_

**Comment by thielpeter** [comment]
Hatte das gleiche Problem, dass die Platzhalter leer waren und der default nicht gegriffen hat
