### ISSUE TITLE
Inhalte kopieren in gleiche Sprache mit vorherigem Löschen verhindern

### ISSUE THREAD

**Issue by TobiasKrais** [tbaddade/redaxo_sprog#64]
Werden Inhalte von einer Sprache in die gleiche Sprache kopiert und vorher der Inhalt gelöscht, kommt das einem Löschen der Inhalte gleich. Ist dieses Feature überhaupt erwünscht? Sollte vorher nicht wenigstens eine Warnmeldung kommen?

**Comment by tbaddade** [comment]
> Sollte vorher nicht wenigstens eine Warnmeldung kommen?

Habe es mit der Redaxo internen JS-Alert-Meldung probiert. Klappt hier nicht, da sich das Popup bereits öffnet. Egal welche Aktion man auswählt, das Popup startet.

Falls du eine andere Lösung parat hättest öffne das Issue gern wieder.

**Comment by TobiasKrais** [comment]
Lösungsmöglichkeiten:

1. Wir könnten ein kleines JS schreiben, das das Feld "Inhalte vorher löschen" deaktiviert, wenn jeweils die gleiche Sprache ausgewählt ist.
2. Wir könnten ein kleines JS schreiben, das die ausgewählte Sprache im jeweils anderen Feld ausblendet.

Was wäre dir lieber?

**Comment by tbaddade** [comment]
Ach moment … Ich habs falsch verstanden.

Ich wäre für **2.** Variante, wobei die Sprache aber disabled gesetzt und nicht ausblendet wird.

Magst du das übernehmen @TobiasKrais ?

**Comment by TobiasKrais** [comment]
Mach ich.
