### ISSUE TITLE
Error beim Kopieren von Artikeln bzw. Metainfos

### ISSUE THREAD

**Issue by fietstouring** [tbaddade/redaxo_sprog#65]
Ich hab lese in einem Modul die Priority des Slices aus, was im normalen Betrieb anstandslos funktioniert. Beim Kopieren mit Hilfe von Sprog gibts ne Fehlermeldung.
Das ist der Code im Modul:
`rex_article_slice::getArticleSliceById(REX_SLICE_ID)->getPriority(); `

Das ist die Fehlermeldung
`Call to a member function getPriority() on null`

Redaxo 5.8.1, Sprog 1.2.0

**Comment by tbaddade** [comment]
Das ist ein Problem in deinem Modul. Du solltest prüfen ob der Slice überhaupt existiert.

```php
$slice = rex_article_slice::getArticleSliceById(REX_SLICE_ID);
if ($slice) {
    echo $slice->getPriority();
}
```
