### ISSUE TITLE
Wildcard::replace sollte auch ohne Begrenzer funktionieren

### ISSUE THREAD

**Issue by Sioweb** [tbaddade/redaxo_sprog#8]
Ho!

Wenn man Wildcard::replace(); nutzt, sollte es ohne die angegebenen Begrenzer funktionieren. 

**Aktuell:**
```
Wildcard::replace('{{Replace This}}');
```

**Schön wäre:**
```
Wildcard::replace('Replace This');
```

**Comment by tbaddade** [comment]
`Wildcard::replace` sollte Text mit mehreren Platzhalter ersetzen.

Bsp.: `Wildcard::replace($this->getValue('description'));`

Jetzt wäre zu überlegen ob man nicht sinnvoller 2 Methoden bereitstellt

**Platzhalter**
 `Wildcard::replace('Five Card Draw');`

**Text**
 `Wildcard::parse('Five {{ Card }} Draw');`

oder eine Methode, wobei der Platzhalter dann eher ohne Leerzeichen kommen sollte
A/ `Wildcard::replace('five.card.draw');`
B/ `Wildcard::replace('Five {{ card }} Draw');`

Für A dann prüfen
```
if (strpos($content, ' ') === false) {
    $content = '{{ ' . $content . ' }}';
}

```

**Comment by Sioweb** [comment]
Ja, eine extra Funktion replaceOne oder ein Zusatzparameter.

**Comment by tbaddade** [comment]
`Wildcard::parse($content)` und `Wildcard::replace($wildcard)` b45ba5ec45e343b1db9c2f731519d7b5a0804580

außerdem [2 neue Funktionen](https://github.com/tbaddade/redaxo_sprog/commit/25b119cee4c1cd383414a2452f12fd407d68bf5c), die die obigen Methoden aufrufen.
`sprogdown($content)`  und `sprogcard($wildcard)`
