### ISSUE TITLE
Ideen, Vorschläge, Nützliches - was wird bei mehrsprachigen Websites noch benötigt

### ISSUE THREAD

**Issue by tbaddade** [tbaddade/redaxo_sprog#9]

**Comment by isospin** [comment]
Super praktisch wäre die Möglichkeit der sprachunabhängigen Metainformationen (Sync) für ausgewählte Felder. Wie im sync_settings Plugin von be_settings...

**Comment by tbaddade** [comment]
@isospin SyncOptionen sind seit kurzem dabei https://github.com/tbaddade/redaxo_sprog/commit/abc2c1c11f354182e6280857aa3b725fa9744b33

Aktuell aber noch nicht über den Installer verfügbar.

**Comment by tbaddade** [comment]
Sind seit einiger Zeit jetzt dabei
